name: "Setup Node.js, pnpm and install dependencies"
description: "Install pnpm, Node.js, and project dependencies"

runs:
  using: "composite"
  steps:
    - uses: pnpm/action-setup@v4
      with:
        run_install: false
    - uses: actions/setup-node@v4
      with:
        node-version-file: .tool-versions
        cache: "pnpm"
        cache-dependency-path: pnpm-lock.yaml
    - name: Install dependencies
      shell: bash
      run: pnpm install
