stages:
  - preflight

.quality: &quality
  image: node:20-alpine
  stage: preflight
  cache:
    key:
      files:
        - pnpm-lock.yaml
    paths:
      - .pnpm-store
  before_script:
    - apk add --no-cache libc6-compat && apk update
    - npm install -g turbo@1.13.0 pnpm@8.15.2
    - pnpm config set store-dir .pnpm-store
    - pnpm install

format:
  <<: *quality
  script:
    - pnpm ci:format

typecheck:
  <<: *quality
  script:
    - pnpm ci:typecheck

lint:
  <<: *quality
  script:
    - pnpm ci:lint

unit_tests:
  <<: *quality
  script:
    - pnpm ci:test

smoke_tests:
  <<: *quality
  script:
    - pnpm ci:smoke

build:
  <<: *quality
  script:
    - pnpm ci:build
