stages:
  - preflight
  - publish

.common: &common
  image: node:20-alpine
  cache:
    key:
      files:
        - pnpm-lock.yaml
    paths:
      - .pnpm-store
  before_script:
    - apk add --no-cache libc6-compat && apk update
    - npm install -g turbo@1.13.0 pnpm@8.15.2
    - pnpm config set store-dir .pnpm-store
    - pnpm install

.quality: &quality
  <<: *common
  stage: preflight

format:
  <<: *quality
  script:
    - pnpm ci:format

typecheck:
  <<: *quality
  script:
    - pnpm ci:typecheck

lint:
  <<: *quality
  script:
    - pnpm ci:lint

unit_tests:
  <<: *quality
  script:
    - pnpm ci:test

smoke_tests:
  <<: *quality
  script:
    - pnpm ci:smoke

build:
  <<: *quality
  script:
    - pnpm ci:build

publish:
  <<: *common
  stage: publish
  script:
    - echo "@flam:registry=https://${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/" > .npmrc
    - echo "//${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}" >> .npmrc
    - pnpm ci:build
    - pnpm ci:publish
