name: release

on:
  push:
    branches:
      - main

env:
  FORCE_COLOR: 1
  NODE_ENV: production

jobs:
  release:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@v4
        with:
          run_install: false
      - uses: actions/setup-node@v4
        with:
          cache-dependency-path: pnpm-lock.yaml
          cache: "pnpm"
          node-version-file: .tool-versions
          registry-url: https://npm.pkg.github.com
          scope: "@jamtartley"
      - run: pnpm install
      - run: pnpm run build
      - run: pnpm run lint
      - run: pnpm run smoke
      - run: pnpm run test
      - run: pnpm run typecheck
      - run: pnpm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
